### ISSUE TITLE
502 Bad Gateway Error after npm publishing

### ISSUE THREAD

**Issue by adamjmoon** [jsonresume/theme-manager#23]
I published them jsonresume-theme-material and now getting 502 Bad Gateway when hitting registered resume: http://registry.jsonresume.org/adammoon?theme=material.  When I run theme-manager locally to the theme works correctly with localhost:3000/theme/material

**Comment by mudassir0909** [comment]
Same problem after I just published `elegant` theme, it works fine on local

**Comment by thomasdavis** [comment]
This was fixed ages ago, love your resume @adamjmoon <3

**Comment by mudassir0909** [comment]
Happening now after I published elegant

**Comment by thomasdavis** [comment]
Looking into it.

**Comment by thomasdavis** [comment]
Pushed the space over again on the themes server, cleaned it up.

http://themes.jsonresume.org/theme/elegant

**Comment by tautologistics** [comment]
This is still happening for new/updates themes.

e.g. http://themes.jsonresume.org/theme/elegant-tautologistics

**Comment by thomasdavis** [comment]
This is back up. Thanks for the notice.

**Comment by mudassir0909** [comment]
http://themes.jsonresume.org/theme/elegant

**Comment by mcarbonneaux** [comment]
Down again?
